# Преобразование таблицы из длинной в широкую

In [1]:
import pandas as pd

## тестовый датафрейм

In [132]:
df = pd.DataFrame({'year':['2025','2025','2025','2024','2024','2026'], 
                   'dep':[1,2,3,1,2,1],
                   'sales':[100,20,25,10,150,10]
                   
                  }
                 )
df

   year  dep  sales
0  2025    1    100
1  2025    2     20
2  2025    3     25
3  2024    1     10
4  2024    2    150
5  2026    1     10

## 1 способ.  Метод unstack() 
проводит преобразование уровней индексов датафрейма в уровни колонок
предварительно придется сгруппировать сырые данные

In [110]:
#группируем
df_groupby= df.groupby(['dep','year']).agg(sales=('sales','sum')).reset_index()
# необходим индекс
df_groupby.set_index(['dep','year'], inplace = True)
# разворачиваем
df_unstack = df_groupby.unstack(fill_value=0)
# Удалим верхний уровень индекса столбцов:
df_unstack.columns=df_unstack.columns.droplevel()
# Сбросим индекс на порядковый номер строки:
df_unstack.reset_index(inplace=True)
# Сбросим название индекса колонок:
df_unstack.columns.name = None
df_unstack

   dep  2024  2025  2026
0    1    10   100    10
1    2   150    20     0
2    3     0    25     0

## 2 способ. Метод pivot_table()

In [92]:
df_pivot = pd.pivot_table(
    data=df, 
    index = 'dep',  # Строки сводной таблицы
    columns = 'year',  # Колонки сводной таблицы
    values = 'sales', # То, что будет агрегироваться
    aggfunc='sum', # Агрегирующая функция 
    fill_value = 0 # None на пересечениях заменяем на 0
).reset_index() #сбрасываем индекс
df_pivot.columns.name = None # cбросим название индекса колонок:
df_pivot.rename(columns={'2024':'sales2024','2025':'sales2025','2026':'sales2026'}, inplace = True) #переименовываем колонки
df_pivot

   dep  sales2024  sales2025  sales2026
0    1         10        100         10
1    2        150         20          0
2    3          0         25          0

## если нужно просто развернуть (поменять местами строки и столбцы)
Cвойство датафрейма .T

In [131]:

df_unstack.set_index('dep').T

dep     1    2   3
2024   10  150   0
2025  100   20  25
2026   10    0   0